### PR TITLE
Code quality improvements (no reformat)

### PR DESCRIPTION
**Pull request by bloom1**
This is a version without all the reformats done by `black`.
I also fixed a typo in a dictionary assignment that may cause a Traceback.

### CODE REVIEW

**Comment by ovenwerks** [comment]
There are a number of bugs mostly caused by differences from 20.04 to 21.10 and my working copy is quite different from git. I will look to see if I can direct merge when I get things working again.

**Comment by ovenwerks** [comment]
The changes look ok to me. If you wish to resolve the conflicts, I can merge them. On holidays off and on so I may not get to things as quick as i could. Thank you for putting up with me :)
There are still a few thinkos for me to fix. Or look at anyway. But I will wait for a while before looking at them and also I hope to get people to test 21.68 anyway. After 2.2 is out, I am willing to look at reformatting (as a single pull with nothing else in it :)

**Comment by bloom1** [comment]
> The changes look ok to me. If you wish to resolve the conflicts, I can merge them. On holidays off and on so I may not get to things as quick as i could. Thank you for putting up with me :)
> There are still a few thinkos for me to fix. Or look at anyway. But I will wait for a while before looking at them and also I hope to get people to test 21.68 anyway. After 2.2 is out, I am willing to look at reformatting (as a single pull with nothing else in it :)

Alright, I will do that in the following days. Thanks a lot :smiley:

**Comment by ovenwerks** [comment]
Ok, I have merged this. Please check convert-studio-controls the first 20 lines to see if this is what you envisioned. I have some other things I need to do.

**Pull request closed without merging**
